version: "3"

services:
  reactlibstorybook:
    build:
      context: ./
      dockerfile: storyDevDockerfile
    container_name: reactlibstorybook
    volumes:
      - .:/home/appuser/react-lib
    ports:
      - "6006:6006"
    networks:
      - app-network

  reactlibprodstorybook:
    build:
      context: ./
      dockerfile: storyProdDockerfile
    ports:
      - "8082:80"
    networks:
      - app-network

  reactlibprodjsdoc:
    build:
      context: ./
      dockerfile: jsdocProdDockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

  reactlibjsdoc:
    build:
      context: ./
      dockerfile: jsdocDevDockerfile
    command: >
      /bin/sh -c "nginx && yarn run build:doc:watch"
    tty: true
    volumes:
      - ./src:/usr/share/nginx/src
      - ./.jsdocbuild:/usr/share/nginx/.jsdocbuild
      - ./package.json:/usr/share/nginx/package.json
      - ./yarn.lock:/usr/share/nginx/yarn.lock
      - ./tsconfig.json:/usr/share/nginx/tsconfig.json
      - ./jsdoc.json:/usr/share/nginx/jsdoc.json
      - ./docs:/usr/share/nginx/html
      - ./.jsdocbuild/nginx_conf/:/etc/nginx/conf.d/

    ports:
      - "8080:80"

networks:
  app-network:
    driver: bridge
